-- Test Data for eTaxi Application
-- This script creates a test passenger, a subscription plan, and subscribes the user to that plan.

-- To use this file, run the following command in your MySQL shell:
-- SOURCE /path/to/your/project/test_data.sql;

-- --------------------------------------------------------

-- 1. CREATE A TEST USER (PASSENGER)
-- We first create a record in the `Users` table.
-- Note: The password used here is 'password123'. You should use a proper hash generated by your application.
-- Example hash for 'password123': '$2y$10$9.p6B5C/m2C1o.a.a.a.a.O9Z9X8Y7V6U5T4S3R2Q1P0O'.

INSERT INTO `Users` (`full_name`, `email`, `password_hash`, `role`, `is_active`)
VALUES
  ('Test Passenger One', 'passenger1@etaxi.com', '$2y$10$9.p6B5C/m2C1o.a.a.a.a.O9Z9X8Y7V6U5T4S3R2Q1P0O', 'passenger', 1);

-- Get the ID of the user we just created to use in the next steps.
SET @passenger_id = LAST_INSERT_ID();

-- --------------------------------------------------------

-- 2. CREATE THE CORRESPONDING PASSENGER ENTRY
-- This links the `Users` record to a `Passengers` record.

INSERT INTO `Passengers` (`passenger_id`, `wallet_balance`)
VALUES
  (@passenger_id, 500.00);

-- --------------------------------------------------------

-- 3. CREATE SUBSCRIPTION PLANS
-- Here we add a couple of plans that passengers can subscribe to.

INSERT INTO `Subscription_Plans` (`plan_name`, `price`, `max_rides`, `max_km_per_ride`, `extra_km_charge_percent`, `extra_ride_charge_percent`, `description`, `is_available`)
VALUES
  ('Monthly Prime', 4000.00, 250, 100, 10.00, 25.00, 'Our best value plan for daily commuters.', 1),
  ('Weekly Pass', 1200.00, 60, 100, 15.00, 35.00, 'Perfect for a busy week of travel.', 1);

-- Get the ID of the 'Monthly Prime' plan for the next step.
SET @plan_id = (SELECT `plan_id` FROM `Subscription_Plans` WHERE `plan_name` = 'Monthly Prime');

-- --------------------------------------------------------

-- 4. SUBSCRIBE THE TEST PASSENGER TO A PLAN
-- This creates the active subscription record, linking the passenger to the plan.

INSERT INTO `Subscriptions` (`passenger_id`, `plan_id`, `start_date`, `end_date`, `rides_taken`, `is_active`)
VALUES
  (@passenger_id, @plan_id, CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 MONTH), 12, 1);

-- --------------------------------------------------------

SELECT 'Test data created successfully!' AS status;
